security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Acme\JobeetBundle\Entity\User, property: username }
 
    encoders:
        Acme\JobeetBundle\Entity\User: sha512