account_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AccountBundle:Default:index }
account_register:
    pattern:  /register
    defaults: { _controller: AccountBundle:Default:register}
account_create:
    pattern:  /create
    defaults: { _controller: AccountBundle:Default:create}
account_redirect:
    pattern: /list
    defaults: { _controller: StoreBundle:Default:list}

account_listu:
    pattern: /listu
    defaults: { _controller: AccountBundle:Default:listu}