parameters:
#    account.example.class: Acme\AccountBundle\Example

services:
#    account.example:
#        class: %account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
